version: "3.7"

# services:
#   rust-zola:
#     container_name: rust-zola
#     build:
#       dockerfile: ./.docker/Dockerfile
#       context: .
#       args:
#         USER_ID: $USER_ID
#     env_file: .env
#     volumes:
#       - .:/home/:ro
#     # ports:
#     #   - "8088:9000"
services:
  zola:
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
      target: zola-base
    command: zola serve --interface 0.0.0.0
    volumes:
      - .:/blog
    ports:
      - '1111:1111'