version: "3.7"

services:
  zola:
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
      target: zola-base
      args:
        USER_ID: $USER_ID
    env_file: .env
    command: zola serve --interface 0.0.0.0
    volumes:
      - .:/blog
    ports:
      - '1111:1111'