
on: push
name: Build and deploy GH Pages
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy
      uses: shalzz/zola-deploy-action@v0.12.0
      env:
        PAGES_BRANCH: gh-pages
        TOKEN: ${{ secrets.PA_TOKEN }}
